version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # UTC 02:00 == KST 11:00
      time: '02:00'
    reviewers:
      - "devjiwonchoi"
    allow:
      - dependency-name: "next"
