version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "devjiwonchoi"
    allow:
      - dependency-name: "next"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
