version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    timezone: 'Asia/Seoul'
    time: '11:00'
    reviewers:
      - 'devjiwonchoi'
    groups:
      canary:
        patterns:
          - 'next'
          - 'eslint-config-next'
      dog-food:
        patterns:
          - '@vercel/*'
