version: 2
updates:
  # Daily update for Dogfooding
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Seoul'
      time: '09:00'
    reviewers:
      - 'devjiwonchoi'
    allow:
      - dependency-name: '@vercel/*'
      - dependency-name: '@next/*'
      - dependency-name: '@ai-sdk/*'
      - dependency-name: 'vercel'
      - dependency-name: 'next'
      - dependency-name: 'eslint-config-next'
      - dependency-name: 'ai'
      - dependency-name: 'turbo'
      - dependency-name: 'geist'
    groups:
      canary:
        patterns:
          - '@next/*'
          - 'next'
          - 'eslint-config-next'
          - 'turbo'
          - 'react'
          - 'react-dom'
      dog-food:
        patterns:
          - '@vercel/*'
          - '@ai-sdk/*'
          - 'vercel'
          - 'ai'
          - 'geist'

  # Monthly update for all dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    # set target-branch to work around configure depbot on same directory '/'
    # x-ref: https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: main
    schedule:
      interval: 'monthly'
    reviewers:
      - 'devjiwonchoi'
    groups:
      prod-deps:
        dependency-type: 'production'
      dev-deps:
        dependency-type: 'development'
