version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Seoul'
      time: '11:00'
    reviewers:
      - 'devjiwonchoi'
    allow:
      - dependency-name: 'next'
      - dependency-name: 'eslint-config-next'
      - dependency-name: '@vercel/*'
      - dependency-name: 'turbo'
      - dependency-name: 'geist'
    groups:
      canary:
        patterns:
          - 'next'
          - 'eslint-config-next'
          - 'turbo'
      dog-foods:
        patterns:
          - '@vercel/*'
          - 'geist'
