version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Seoul'
      time: '09:00'
    reviewers:
      - 'devjiwonchoi'
    allow:
      - dependency-name: '@vercel/*'
      - dependency-name: '@ai-sdk/*'
      - dependency-name: 'next'
      - dependency-name: 'ai'
      - dependency-name: 'turbo'
      - dependency-name: 'geist'
    groups:
      canary:
        patterns:
          - 'next'
          - 'turbo'
      dog-food:
        patterns:
          - '@vercel/*'
          - '@ai-sdk/*'
          - 'ai'
          - 'geist'
