name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  playwright-e2e:
    name: playwright-e2e
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install playwright browsers
        run: pnpm playwright install --with-deps

      - name: Build
        run: pnpm build

      - name: Start Next.js
        run: pnpm start -p 3000

      - name: Run tests
        run: pnpm test:e2e
