name: lighthouse
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'pnpm-lock.yaml'
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build
      - run: npx lhci autorun