name: Lighthouse
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'pnpm-lock.yaml'

env:
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run Lighthouse Desktop audits
        run: pnpm lhci:desktop --collect.startServerCommand="pnpm build && pnpm start" --collect.url="http://localhost:3000"

      - name: Run Lighthouse Mobile audits
        run: pnpm lhci --collect.startServerCommand="pnpm build && pnpm start" --collect.url="http://localhost:3000"
