name: Playwright Tests

on:
  deployment_status:

jobs:
  playwright:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
        shard-index: [1, 2, 3, 4]
        shard-total: [4]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run tests
        run: pnpm test:e2e --shard=${{ matrix.shard-index }}/${{ matrix.shard-total }}
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}